# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_footnote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footnote',
            name='body',
        ),
        migrations.AddField(
            model_name='footnote',
            name='note',
            field=djangocms_text_ckeditor.fields.HTMLField(default=b'Test'),
        ),
        migrations.AlterField(
            model_name='footnote',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_footnote_footnote', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
