# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_footnote', '0002_auto_20190325_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footnote',
            old_name='note',
            new_name='body',
        ),
    ]
