# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_footnote', '0003_auto_20190325_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='footnote',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_footnote_footnote', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
